spring:
  application:
    name: grass-ai-agent
  # 数据库连接池
  datasource:
    dynamic:
      primary: mysql
      strict: false
      datasource:
        mysql:
          url: jdbc:mysql://175.24.73.151:3306/grass_ai_agent?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
          username: grass_ai_agent_root
          password: grass_ai_agent_root_123456
          driver-class-name: com.mysql.cj.jdbc.Driver
        postgresql:
          url: jdbc:postgresql://175.24.73.151:5432/ai_agent_pg
          username: ai_agent_pg_root
          password: ai_agent_pg_root_123456!
          driver-class-name: org.postgresql.Driver
          hikari:
            maximum-pool-size: 10
            connection-timeout: 30000

  ai:
    dashscope:
      api-key: sk-eb1069f36bcd4af0bd638c5e6fa4f026
      chat:
        options:
          model: qwen-plus
      # 多模态（读图）模型，用于图片解释
      multimodal:
        model: qwen-vl-plus
    vectorstore:
      pgvector:
        # 向量表配置
        dimensions: 1024  # DashScope 默认 Embedding 模型输出 1024 维
        distance-type: COSINE_DISTANCE  # 可选: cosine/l2/inner
        initialize-schema: false  # 自动初始化表结构
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        index-type: HNSW

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

server:
  port: 8123
  servlet:
    context-path: /api
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.grass.grassaiagent.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn

# searchApi
search-api:
  api-key: rNFWvAY2puMxosqTXpkvjUAZ
  api-url: https://www.searchapi.io/api/v1/search

