spring:
  ai:
    mcp:
      server:
        name: grass-pdf-to-image-mcp-server
        version: 1.0.0
        type: sync
        stdio: true
  main:
    web-application-type: none
    banner-mode: off
